---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Include slurm_c1_vars
      include_vars: slurm_c1_vars.yaml
    - name: Provision slurm head
      debug:
        msg: "SLURM HEAD"
    - name: Check for munge key
      stat:
        path: /etc/munge/munge.key
      register: munge_key_stat
    - name: Create munge key
      command: /usr/sbin/create-munge-key
      when: not munge_key_stat.stat.exists
    # - name: Create local setup/etc/munge
    #   delegate_to: localhost
    #   command: mkdir -pv setup/etc/munge
    - name: Fetch munge key
      fetch:
        src: /etc/munge/munge.key
        dest: setup
    - name: Start munge
      service:
        name: munge
        enabled: yes
        state: restarted
    - name: Copy slurm.conf
      template:
        src: etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: u=rw,go=r
    - name: Copy slurmdbd.conf
      template:
        src: etc/slurm/slurmdbd.conf
        dest: /etc/slurm/slurmdbd.conf
        owner: root
        group: root
        mode: u=rw,go=
    - name: Start slurmctld
      service:
        name: slurmctld
        enabled: yes
        state: restarted
