---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Include slurm_c1_vars
      include_vars: slurm_c1_vars.yaml
    - name: Provision slurm db
      debug:
        msg: "SLURM DB"
    - name: Install packages
      yum:
        state: latest
        name:
          - mariadb
          - mariadb-server
    - name: Copy innodb.cnf
      copy:
        src: slurm-c1-db1/etc/my.cnf.d/innodb.cnf
        dest: /etc/my.cnf.d/innodb.cnf
        owner: root
        group: root
        mode: ug=rw,g=r
    - name: Start mariadb
      service:
        name: mariadb
        enabled: yes
        state: restarted
    # This is maraidb 5.5 that defaults to no local root password
    - name: Configure mariadb databases
      shell: |
        mysql -u root << EOF
        use mysql;
        grant all privileges on * TO 'root'@'%' identified by '{{ mysql_root_password }}' with grant option;
        flush privileges;
        EOF
    - name: Check for slurm_acct_db
      shell: 'echo "show databases;" | mysql -u root | grep slurm_acct_db'
      register: check_slurm_acct_db_result
    - name: Create slurm_acct_db database
      shell: |
        mysql -u root << EOF
        create database slurm_acct_db;
        grant all privileges on slurm_acct_db.* TO 'slurm'@'%' identified by '{{ slurmdb_password }}' with grant option;
        EOF
      # 0 matches, 1 no matches, 2+ error
      when: check_slurm_acct_db_result.rc == 1
    # - name: Start munge
    #   service:
    #     name: munge
    #     enabled: yes
    #     state: restarted
    - name: Copy slurm.conf
      template:
        src: etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: u=rw,go=r
    - name: Copy slurmdbd.conf
      template:
        src: etc/slurm/slurmdbd.conf
        dest: /etc/slurm/slurmdbd.conf
        owner: root
        group: root
        mode: u=rw,go=
    - name: Start slurmdbd
      service:
        name: slurmdbd
        enabled: yes
        state: restarted
