---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Provision slurm head
      debug:
        msg: "SLURM HEAD"
    - name: Check for munge key
      stat:
        path: /etc/munge/munge.key
      register: munge_key_stat
    - name: Create munge key
      command: /usr/sbin/create-munge-key
      when: not munge_key_stat.stat.exists
    # - name: Create local setup/etc/munge
    #   delegate_to: localhost
    #   command: mkdir -pv setup/etc/munge
    - name: Fetch munge key
      fetch:
        src: /etc/munge/munge.key
        dest: setup
        